### ISSUE TITLE
Overview showing wrong basal rate when on basel rate is switched to default basal rate from profile

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#66] opened 2021-07-28 19:53 UTC
**AndroidAPS 2.8.2.2-dev**
Build: 2e8a81f
Flavor: fullrelease

**Phone:**
Samsung Note9 (SM-N960F, Android 10)

**Problem description:**
When on standard basal rate from profile, overview shows the wrong basal rate.

_Additional "context" info:_
DASH tab does show the actual basel rate set on the pump

**Repro:**
When BG value is stable, set a temporary target at the current BG value.
Most likely AAPS will switch to standard basal rate from profile.
Then check basal rate on overview and compare with basal rate reported on DASH tab.

**Comment by vanelsberg** [comment] 2021-07-29 21:10
Might be related to switching profile percentage (e.g switching from 100 to 110%)
as well as overview not correctly updating?

Seeing a lot of wrong 0.50's at 110% (while profile default = 0.45)
Still hard to repro.

**Comment by avereha** [comment] 2021-08-07 18:36
Could this be duplicate of https://github.com/0pen-dash/AndroidAPS/issues/68 ?

**Comment by vanelsberg** [comment] 2021-08-07 19:48
Could be. Reading back the description of this issue it does not make sense. 
Not sure what I was trying to say, but with a standard basalrate of 0.45 in profile, a 110% profile would amount to 0.50u?
So maybe this is not a bug at all?

**Comment by vanelsberg** [comment] 2021-08-07 19:51
Maybe best to close this issue as not reproduceable.
Will open in case I run into it, then with some additional information.

**Closed** 2021-08-07 20:05 UTC
Labels: AAPS
