### ISSUE TITLE
Overview reporting impossible basal rate (read: not multiple of 0.05U)

### ISSUE THREAD

**Issue by vanelsberg** [0pen-dash/AndroidAPS#68] opened 2021-07-28 20:05 UTC
**AndroidAPS 2.8.2.2-dev**
Build: 2e8a81f
Flavor: fullrelease

**Phone:**
Samsung Note9 (SM-N960F, Android 10)

**Problem description:**
Overview reports impossible temporary basal rate (read: not multiple of 0.05U)

_Repro:_
Have not found a good repro.
The invalid TBR occasionally appear, most of the time they are OK.

**Comment by vanelsberg** [comment] 2021-07-29 21:05
Might be related to running/switching profile percentage (e.g. 110%)?

**Comment by avereha** [comment] 2021-08-05 20:07
Do we get the same issue with the virtual pump? 
I'm trying to understand if this is Dash or AAPS specific.

**Comment by vanelsberg** [comment] 2021-08-05 21:47
Have not tried virtual pump. Not sure if it can repro on that, but will check.
EROS/DASH boluses can only be a multiple of 0.05u (one tick). Not sure how this is for other pumps?

I know we had this bug on EROS. Can not remember if this was fixed on driver or main.

**Comment by avereha** [comment] 2021-09-12 12:05
We will need logs and screenshots for this. Is this a duplicate of https://github.com/0pen-dash/AndroidAPS/issues/93?

**Comment by avereha** [comment] 2021-09-24 21:29
Please reopen if you notice this again.
Maybe it was already fixed.

**Closed by avereha** 2021-09-24 21:29 UTC
Labels: bug, AAPS
